-- =====================================================================
-- 데모 규모 시드 (2/2): 작업 전 점검(TBM, 제38조 작업계획서), 사고
--
-- 작업 전 점검 41건(V10의 1건 포함 42): 지난 작업일은 전부 완료(CLOSED), 승인(오늘 이후),
-- 승인 대기(오늘, 다음 작업일), 작업 보류(사고 6 후속). 지게차 하역과 천장크레인 인양은 안전보건규칙
-- 제38조 대상이라 서식 이름이 작업계획서로 갈리고, 관리감독자가 작업지휘자(제39조)를 맡는다.
-- 승인자는 그 작업의 관리감독자(반장, 팀장)다. 승인은 전 평일 오후 또는 당일 07:30~08:15,
-- TBM은 당일 07:50~08:40(승인 뒤)이다. 미이행 조치가 남은 설비의 작업은 승인 조건(잠정조치)을 단다.
--
-- 사고 5건(V10의 1건 포함 6): 끼임 휴업 2일, 물체에 맞음 휴업 1일, 부딪힘 아차사고, 화재 휴업 6일(조사표 제출),
-- 천장크레인 물체에 맞음 휴업 42일(조사표 작성 필요, 수시평가 작성 중, 다음 인양 작업 보류).
-- 원인은 불안전 상태와 불안전 행동으로 나눈 사실, 재발방지는 "무엇을 (담당, 기한 YYYY-MM-DD)" 형식이다.
-- =====================================================================

-- 평일 보정 함수(이 마이그레이션 세션 안에서만 쓴다). 주말과 공휴일(2025~2027, 대체공휴일, 근로자의 날)을
-- 피한다. 오늘보다 앞선 날은 직전 평일로, 오늘 이후는 다음 평일로 민다. 날짜 순서는 뒤집히지 않는다
CREATE OR REPLACE FUNCTION pg_temp.saife_wd(d date) RETURNS date LANGUAGE plpgsql STABLE AS $$
DECLARE
  r    date := d;
  step int  := CASE WHEN d < CURRENT_DATE THEN -1 ELSE 1 END;
BEGIN
  WHILE EXTRACT(ISODOW FROM r) >= 6 OR r = ANY ('{2025-01-01,2025-01-27,2025-01-28,2025-01-29,2025-01-30,2025-03-01,2025-03-03,2025-05-01,2025-05-05,2025-05-06,2025-06-03,2025-06-06,2025-08-15,2025-10-03,2025-10-05,2025-10-06,2025-10-07,2025-10-08,2025-10-09,2025-12-25,2026-01-01,2026-02-16,2026-02-17,2026-02-18,2026-03-01,2026-03-02,2026-05-01,2026-05-05,2026-05-24,2026-05-25,2026-06-03,2026-06-06,2026-07-17,2026-08-15,2026-08-17,2026-09-24,2026-09-25,2026-09-26,2026-10-03,2026-10-05,2026-10-09,2026-12-25,2027-01-01,2027-02-06,2027-02-07,2027-02-08,2027-02-09,2027-03-01,2027-05-01,2027-05-05,2027-05-13,2027-06-06,2027-07-17,2027-08-15,2027-08-16,2027-09-14,2027-09-15,2027-09-16,2027-10-03,2027-10-04,2027-10-09,2027-10-11,2027-12-25,2027-12-27}'::date[]) LOOP
    r := r + step;
  END LOOP;
  RETURN r;
END $$;

-- 다음 평일(그날 제외)
CREATE OR REPLACE FUNCTION pg_temp.saife_next(d date) RETURNS date LANGUAGE plpgsql STABLE AS $$
DECLARE
  r date := d + 1;
BEGIN
  WHILE EXTRACT(ISODOW FROM r) >= 6 OR r = ANY ('{2025-01-01,2025-01-27,2025-01-28,2025-01-29,2025-01-30,2025-03-01,2025-03-03,2025-05-01,2025-05-05,2025-05-06,2025-06-03,2025-06-06,2025-08-15,2025-10-03,2025-10-05,2025-10-06,2025-10-07,2025-10-08,2025-10-09,2025-12-25,2026-01-01,2026-02-16,2026-02-17,2026-02-18,2026-03-01,2026-03-02,2026-05-01,2026-05-05,2026-05-24,2026-05-25,2026-06-03,2026-06-06,2026-07-17,2026-08-15,2026-08-17,2026-09-24,2026-09-25,2026-09-26,2026-10-03,2026-10-05,2026-10-09,2026-12-25,2027-01-01,2027-02-06,2027-02-07,2027-02-08,2027-02-09,2027-03-01,2027-05-01,2027-05-05,2027-05-13,2027-06-06,2027-07-17,2027-08-15,2027-08-16,2027-09-14,2027-09-15,2027-09-16,2027-10-03,2027-10-04,2027-10-09,2027-10-11,2027-12-25,2027-12-27}'::date[]) LOOP
    r := r + 1;
  END LOOP;
  RETURN r;
END $$;

-- 직전 평일(그날 제외). 작업 전 점검은 전 평일 오후에 작성한다
CREATE OR REPLACE FUNCTION pg_temp.saife_prev(d date) RETURNS date LANGUAGE plpgsql STABLE AS $$
DECLARE
  r date := d - 1;
BEGIN
  WHILE EXTRACT(ISODOW FROM r) >= 6 OR r = ANY ('{2025-01-01,2025-01-27,2025-01-28,2025-01-29,2025-01-30,2025-03-01,2025-03-03,2025-05-01,2025-05-05,2025-05-06,2025-06-03,2025-06-06,2025-08-15,2025-10-03,2025-10-05,2025-10-06,2025-10-07,2025-10-08,2025-10-09,2025-12-25,2026-01-01,2026-02-16,2026-02-17,2026-02-18,2026-03-01,2026-03-02,2026-05-01,2026-05-05,2026-05-24,2026-05-25,2026-06-03,2026-06-06,2026-07-17,2026-08-15,2026-08-17,2026-09-24,2026-09-25,2026-09-26,2026-10-03,2026-10-05,2026-10-09,2026-12-25,2027-01-01,2027-02-06,2027-02-07,2027-02-08,2027-02-09,2027-03-01,2027-05-01,2027-05-05,2027-05-13,2027-06-06,2027-07-17,2027-08-15,2027-08-16,2027-09-14,2027-09-15,2027-09-16,2027-10-03,2027-10-04,2027-10-09,2027-10-11,2027-12-25,2027-12-27}'::date[]) LOOP
    r := r - 1;
  END LOOP;
  RETURN r;
END $$;

-- ── 작업 전 점검 ───────────────────────────────────────────────────
-- 1번(V10, 사고 1의 고소작업대 조명 교체)은 날짜, 시각, 작업자, 현장 확인을 다시 고정한다
UPDATE work_plan SET work_date = pg_temp.saife_wd((CURRENT_DATE - 45)), work_hours = 4.0, method = '고소작업대로 상승, 기존 조명 탈거, 신규 조명 설치와 결선, 점등 확인', notes = '작업대 결손 구간 출입 금지', briefing = '작업: 2층 조립구역 조명 교체 / 공장동 2층 조립구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 45)), 'YYYY-MM-DD') || chr(10) || '작업자: 박민수 설비팀장, 이도현 기사' || chr(10) || '대상 설비: 고소작업대 (공장동 2층 조립구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 작업대 안전난간이 빠진 곳으로 떨어질 수 있습니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 작업대 안전난간을 보수한 뒤 올라갑니다' || chr(10) || '2. 안전모, 안전대를 착용합니다' || chr(10) || '미이행 조치: 고소작업대 작업대 안전난간 보수 (기한 ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 55)), 'YYYY-MM-DD') || ')' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', briefing_ack_at = ((pg_temp.saife_wd((CURRENT_DATE - 45)) + TIME '08:39') AT TIME ZONE 'Asia/Seoul'), status = 'CLOSED', approval_note = '결손 구간 출입 금지 표시, 안전대 상시 체결', approved_by = '박민수', approved_at = ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 45))) + TIME '15:33') AT TIME ZONE 'Asia/Seoul'), closed_at = ((pg_temp.saife_wd((CURRENT_DATE - 45)) + TIME '16:28') AT TIME ZONE 'Asia/Seoul'), warning_note = NULL, created_at = ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 45))) + TIME '13:16') AT TIME ZONE 'Asia/Seoul') WHERE id = 1;
DELETE FROM work_plan_hazard WHERE work_plan_id = 1;
INSERT INTO work_plan (id, site_id, process_id, equipment_id, work_name, work_place, work_date, work_hours, method, notes, briefing, briefing_ack_at, status, approval_note, approved_by, approved_at, closed_at, warning_note, created_at) VALUES
  (2, 1, 7, 24, '지붕 배수구 낙엽 청소', '공장동 옥상', pg_temp.saife_wd((CURRENT_DATE - 355)), 3.0, '지붕 진입, 안전대 체결, 배수구 청소, 하강', '강풍, 강우 시 작업 중지', '작업: 지붕 배수구 낙엽 청소 / 공장동 옥상 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 355)), 'YYYY-MM-DD') || chr(10) || '작업자: 박민수 설비팀장, 강태호 기사' || chr(10) || '대상 설비: 지붕 작업 구역 (공장동 옥상)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 높이 6m 지붕 작업입니다. 떨어지면 크게 다칩니다' || chr(10) || '2. 채광창은 사람 무게를 버티지 못합니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 안전대를 구명줄에 걸고 작업합니다' || chr(10) || '2. 채광창 위로 올라서지 않습니다' || chr(10) || '3. 안전모, 안전대를 착용합니다' || chr(10) || '미이행 조치: 지붕 용마루 구명줄(안전대 부착설비) 설치 (기한 ' || to_char(GREATEST(pg_temp.saife_wd((pg_temp.saife_wd((CURRENT_DATE - INTERVAL '13 months')::date) + 60)), pg_temp.saife_next(pg_temp.saife_wd((CURRENT_DATE - INTERVAL '13 months')::date))), 'YYYY-MM-DD') || ')' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 355)) + TIME '08:13') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', '2인 1조, 용마루 임시 구명줄 설치 후 작업', '박민수', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 355))) + TIME '16:03') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 355)) + TIME '11:37') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 355))) + TIME '13:46') AT TIME ZONE 'Asia/Seoul')),
  (3, 1, 5, 16, '제관 구조물 인양 (0.8톤)', '공장동 1층 제관구역', pg_temp.saife_wd((CURRENT_DATE - 340)), 2.0, '줄걸이 용구와 훅 해지장치 점검, 신호수 배치와 출입 통제선 설치, 인양, 착지 확인 후 줄걸이 해체', '인양 반경 출입 통제, 신호는 신호수 1명', '작업: 제관 구조물 인양 (0.8톤) / 공장동 1층 제관구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 340)), 'YYYY-MM-DD') || chr(10) || '작업자: 정민준 용접반장, 서하준 주임, 한도윤 사원' || chr(10) || '대상 설비: 천장크레인 1호 (공장동 1층 제관구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 인양물이 떨어지거나 흔들려 사람에 맞을 수 있습니다' || chr(10) || '2. 훅 해지장치나 슬링이 손상되면 줄걸이가 빠질 수 있습니다' || chr(10) || '3. 인양물 아래로 들어가면 피할 곳이 없습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 줄걸이 용구와 훅 해지장치를 확인하고 인양합니다' || chr(10) || '2. 신호수 한 명이 신호하고 인양물 아래 출입을 막습니다' || chr(10) || '3. 안전모, 안전화를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 340)) + TIME '08:21') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '정민준', ((pg_temp.saife_wd((CURRENT_DATE - 340)) + TIME '08:11') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 340)) + TIME '10:37') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 340))) + TIME '13:09') AT TIME ZONE 'Asia/Seoul')),
  (4, 1, 3, 5, '원자재 입고 하역', '창고동 1층', pg_temp.saife_wd((CURRENT_DATE - 330)), 2.0, '운행 경로와 보행 통로 확인, 유도자 배치, 하역, 적재 높이 확인, 포크 내리고 주차', '보행자는 구획 통로로, 후진 시 유도자 신호', '작업: 원자재 입고 하역 / 창고동 1층 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 330)), 'YYYY-MM-DD') || chr(10) || '작업자: 최동훈 창고반장, 오지훈 주임, 윤서연 사원' || chr(10) || '대상 설비: 전동 지게차 1호 (창고동 1층)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 지게차 후진 중 보행자와 부딪힐 수 있습니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 보행자는 구획된 통로로 다니고 유도자가 신호합니다' || chr(10) || '2. 안전모, 안전화를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 330)) + TIME '08:20') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '최동훈', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 330))) + TIME '16:05') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 330)) + TIME '10:44') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 330))) + TIME '14:22') AT TIME ZONE 'Asia/Seoul')),
  (5, 1, 1, 2, '도장 부스 필터 교체', '공장동 후면 차양부', pg_temp.saife_wd((CURRENT_DATE - 318)), 2.0, '배기 팬 정지, 필터 탈거, 신규 필터 장착, 배기 가동 확인', '작업 중 배기 팬 정지 금지', '작업: 도장 부스 필터 교체 / 공장동 후면 차양부 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 318)), 'YYYY-MM-DD') || chr(10) || '작업자: 김철수 생산반장, 장우진 사원' || chr(10) || '대상 설비: 도장 부스 1호 (공장동 후면 차양부)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 우레탄 도료 증기는 불이 잘 붙고, 들이마시면 어지러울 수 있습니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 창과 문을 열어 환기하고, 주변에 불씨를 두지 않습니다' || chr(10) || '2. 방독마스크를 착용합니다' || chr(10) || '' || chr(10) || '화학물질: 우레탄 도료, 추정 주성분 톨루엔, 제품 MSDS 확인 필요, 유해성 H225 고인화성 액체 및 증기' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 318)) + TIME '07:55') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '김철수', ((pg_temp.saife_wd((CURRENT_DATE - 318)) + TIME '07:33') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 318)) + TIME '10:14') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 318))) + TIME '13:43') AT TIME ZONE 'Asia/Seoul')),
  (6, 1, 2, 7, '프레스 1호 금형 교체', '공장동 1층 가공구역', pg_temp.saife_wd((CURRENT_DATE - 305)), 3.0, '전원 차단과 잠금, 안전블록 설치, 금형 교체, 시운전', '금형 교체 중 기동 스위치 잠금, 열쇠는 작업자 휴대', '작업: 프레스 1호 금형 교체 / 공장동 1층 가공구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 305)), 'YYYY-MM-DD') || chr(10) || '작업자: 이영희 가공반장, 장우진 사원' || chr(10) || '대상 설비: 기계식 프레스 1호 (공장동 1층 가공구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 위에서 물건이 떨어질 수 있습니다' || chr(10) || '2. 금형 사이에 손이 들어가면 끼일 수 있습니다' || chr(10) || '3. 방호장치를 끄거나 떼고 작업하면 손이 위험한계에 들어갑니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 인양물이나 적재물 아래로 들어가지 않습니다' || chr(10) || '2. 금형 교체 전에 전원을 끄고 잠급니다' || chr(10) || '3. 작업에 맞는 보호구를 갖추고 시작합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 305)) + TIME '08:24') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '이영희', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 305))) + TIME '16:24') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 305)) + TIME '11:40') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 305))) + TIME '15:05') AT TIME ZONE 'Asia/Seoul')),
  (7, 1, 2, 11, '공기압축기 V벨트 교체', '공장동 1층 가공구역', pg_temp.saife_wd((CURRENT_DATE - 290)), 2.0, '전원 차단과 잠금, 덮개 탈거, 벨트 교체, 덮개 재고정, 시운전', '정비 중 표지 부착, 전원 잠금 열쇠는 작업자 휴대', '작업: 공기압축기 V벨트 교체 / 공장동 1층 가공구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 290)), 'YYYY-MM-DD') || chr(10) || '작업자: 박민수 설비팀장, 강태호 기사' || chr(10) || '대상 설비: 공기압축기 1호 (공장동 1층 가공구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 회전부에 손이나 옷이 말려 들어갈 수 있습니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 정비 전에 전원을 끄고 잠급니다' || chr(10) || '2. 작업 후 덮개를 다시 고정합니다' || chr(10) || '3. 작업에 맞는 보호구를 갖추고 시작합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 290)) + TIME '08:14') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '박민수', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 290))) + TIME '16:38') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 290)) + TIME '10:46') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 290))) + TIME '14:06') AT TIME ZONE 'Asia/Seoul')),
  (8, 1, 5, 16, '금형 인양 (1.2톤)', '공장동 1층 제관구역', pg_temp.saife_wd((CURRENT_DATE - 271)), 2.0, '줄걸이 용구와 훅 해지장치 점검, 신호수 배치와 출입 통제선 설치, 인양, 착지 확인 후 줄걸이 해체', '인양 반경 출입 통제, 신호는 신호수 1명', '작업: 금형 인양 (1.2톤) / 공장동 1층 제관구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 271)), 'YYYY-MM-DD') || chr(10) || '작업자: 정민준 용접반장, 서하준 주임, 한도윤 사원' || chr(10) || '대상 설비: 천장크레인 1호 (공장동 1층 제관구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 인양물이 떨어지거나 흔들려 사람에 맞을 수 있습니다' || chr(10) || '2. 훅 해지장치나 슬링이 손상되면 줄걸이가 빠질 수 있습니다' || chr(10) || '3. 인양물 아래로 들어가면 피할 곳이 없습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 줄걸이 용구와 훅 해지장치를 확인하고 인양합니다' || chr(10) || '2. 신호수 한 명이 신호하고 인양물 아래 출입을 막습니다' || chr(10) || '3. 안전모, 안전화를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 271)) + TIME '08:16') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '정민준', ((pg_temp.saife_wd((CURRENT_DATE - 271)) + TIME '08:06') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 271)) + TIME '10:55') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 271))) + TIME '13:09') AT TIME ZONE 'Asia/Seoul')),
  (9, 1, 3, 17, '완제품 출하 상차', '창고동 1층', pg_temp.saife_wd((CURRENT_DATE - 262)), 3.0, '운행 경로와 보행 통로 확인, 유도자 배치, 하역, 적재 높이 확인, 포크 내리고 주차', '보행자는 구획 통로로, 후진 시 유도자 신호', '작업: 완제품 출하 상차 / 창고동 1층 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 262)), 'YYYY-MM-DD') || chr(10) || '작업자: 최동훈 창고반장, 오지훈 주임, 윤서연 사원' || chr(10) || '대상 설비: 전동 지게차 2호 (창고동 1층)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 지게차 후진 중 보행자와 부딪힐 수 있습니다' || chr(10) || '2. 적재 높이를 넘기면 화물이 떨어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 보행자는 구획된 통로로 다니고 유도자가 신호합니다' || chr(10) || '2. 포크를 내리고 이동하며 정해진 적재 높이를 넘기지 않습니다' || chr(10) || '3. 안전모, 안전화를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 262)) + TIME '08:26') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '최동훈', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 262))) + TIME '15:47') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 262)) + TIME '12:01') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 262))) + TIME '14:05') AT TIME ZONE 'Asia/Seoul')),
  (10, 1, 2, 7, '프레스 1호 금형 교체', '공장동 1층 가공구역', pg_temp.saife_wd((CURRENT_DATE - 248)), 3.0, '전원 차단과 잠금, 안전블록 설치, 금형 교체, 시운전', '금형 교체 중 기동 스위치 잠금, 열쇠는 작업자 휴대', '작업: 프레스 1호 금형 교체 / 공장동 1층 가공구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 248)), 'YYYY-MM-DD') || chr(10) || '작업자: 이영희 가공반장, 장우진 사원' || chr(10) || '대상 설비: 기계식 프레스 1호 (공장동 1층 가공구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 위에서 물건이 떨어질 수 있습니다' || chr(10) || '2. 금형 사이에 손이 들어가면 끼일 수 있습니다' || chr(10) || '3. 방호장치를 끄거나 떼고 작업하면 손이 위험한계에 들어갑니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 인양물이나 적재물 아래로 들어가지 않습니다' || chr(10) || '2. 금형 교체 전에 전원을 끄고 잠급니다' || chr(10) || '3. 작업에 맞는 보호구를 갖추고 시작합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 248)) + TIME '08:19') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '이영희', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 248))) + TIME '16:42') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 248)) + TIME '11:49') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 248))) + TIME '13:24') AT TIME ZONE 'Asia/Seoul')),
  (11, 1, 2, 7, '프레스 1호 금형 교체 후 시운전', '공장동 1층 가공구역', pg_temp.saife_wd((CURRENT_DATE - 240)), 2.0, '안전블록 제거, 저속 시운전, 소재 위치 확인, 양산 전환', '금형 교체 중 기동 스위치 잠금, 열쇠는 작업자 휴대', '작업: 프레스 1호 금형 교체 후 시운전 / 공장동 1층 가공구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 240)), 'YYYY-MM-DD') || chr(10) || '작업자: 이영희 가공반장, 장우진 사원' || chr(10) || '대상 설비: 기계식 프레스 1호 (공장동 1층 가공구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 위에서 물건이 떨어질 수 있습니다' || chr(10) || '2. 금형 사이에 손이 들어가면 끼일 수 있습니다' || chr(10) || '3. 방호장치를 끄거나 떼고 작업하면 손이 위험한계에 들어갑니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 인양물이나 적재물 아래로 들어가지 않습니다' || chr(10) || '2. 금형 교체 전에 전원을 끄고 잠급니다' || chr(10) || '3. 작업에 맞는 보호구를 갖추고 시작합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 240)) + TIME '08:14') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '이영희', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 240))) + TIME '15:37') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 240)) + TIME '11:52') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 240))) + TIME '13:29') AT TIME ZONE 'Asia/Seoul')),
  (12, 1, 6, 23, '혼합기 교반 날개 청소', '공장동 후면 조색실', pg_temp.saife_wd((CURRENT_DATE - 225)), 2.0, '전원 차단과 잠금, 잔여 도료 배출, 날개 세척, 덮개 닫고 시운전', '작업 중 조색실 출입문 개방', '작업: 혼합기 교반 날개 청소 / 공장동 후면 조색실 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 225)), 'YYYY-MM-DD') || chr(10) || '작업자: 김철수 생산반장, 강태호 기사' || chr(10) || '대상 설비: 페인트 혼합기 (공장동 후면 조색실)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 우레탄 도료 증기는 불이 잘 붙고, 들이마시면 어지러울 수 있습니다' || chr(10) || '2. 회전부에 손이나 옷이 말려 들어갈 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 창과 문을 열어 환기하고, 주변에 불씨를 두지 않습니다' || chr(10) || '2. 정비 전에 전원을 끄고 잠급니다' || chr(10) || '3. 방독마스크를 착용합니다' || chr(10) || '' || chr(10) || '화학물질: 우레탄 도료, 추정 주성분 톨루엔, 제품 MSDS 확인 필요, 유해성 H225 고인화성 액체 및 증기' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 225)) + TIME '08:11') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '김철수', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 225))) + TIME '16:02') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 225)) + TIME '10:32') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 225))) + TIME '15:10') AT TIME ZONE 'Asia/Seoul')),
  (13, 1, 7, 24, '지붕 판넬 볼트 보수', '공장동 옥상', pg_temp.saife_wd((CURRENT_DATE - 210)), 4.0, '지붕 진입, 구명줄에 안전대 체결, 볼트 교체, 하강', '강풍, 강우 시 작업 중지', '작업: 지붕 판넬 볼트 보수 / 공장동 옥상 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 210)), 'YYYY-MM-DD') || chr(10) || '작업자: 박민수 설비팀장, 강태호 기사' || chr(10) || '대상 설비: 지붕 작업 구역 (공장동 옥상)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 높이 6m 지붕 작업입니다. 떨어지면 크게 다칩니다' || chr(10) || '2. 채광창은 사람 무게를 버티지 못합니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 안전대를 구명줄에 걸고 작업합니다' || chr(10) || '2. 채광창 위로 올라서지 않습니다' || chr(10) || '3. 안전모, 안전대를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 210)) + TIME '08:03') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '박민수', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 210))) + TIME '15:28') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 210)) + TIME '13:28') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 210))) + TIME '13:03') AT TIME ZONE 'Asia/Seoul')),
  (14, 1, 4, 19, '2층 조립구역 덕트 행거 설치', '공장동 2층 조립구역', pg_temp.saife_wd((CURRENT_DATE - 196)), 4.0, '비계 설치와 바퀴 고정, 안전난간 확인, 행거 설치, 비계 해체', '비계 위 자재는 당일 사용량만', '작업: 2층 조립구역 덕트 행거 설치 / 공장동 2층 조립구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 196)), 'YYYY-MM-DD') || chr(10) || '작업자: 박민수 설비팀장, 장우진 사원' || chr(10) || '대상 설비: 이동식 비계 1호 (공장동 2층 조립구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 높이 3.6m 작업입니다. 떨어지면 크게 다칩니다' || chr(10) || '2. 바퀴가 고정되지 않으면 비계가 움직여 떨어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 바퀴 브레이크와 안전난간을 확인하고 올라갑니다' || chr(10) || '2. 안전모를 착용합니다' || chr(10) || '미이행 조치: 이동식 비계 사용 전 바퀴 브레이크, 안전난간 점검표 운영 (기한 ' || to_char(GREATEST(pg_temp.saife_wd((pg_temp.saife_wd((CURRENT_DATE - 198)) + 14)), pg_temp.saife_next(pg_temp.saife_wd((CURRENT_DATE - 198)))), 'YYYY-MM-DD') || ')' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 196)) + TIME '08:21') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', '점검표 운영 전까지 관리감독자가 바퀴 브레이크와 안전난간을 직접 확인', '박민수', ((pg_temp.saife_wd((CURRENT_DATE - 196)) + TIME '08:11') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 196)) + TIME '13:43') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 196))) + TIME '14:12') AT TIME ZONE 'Asia/Seoul')),
  (15, 1, 5, 16, '제관 구조물 인양 (1.5톤)', '공장동 1층 제관구역', pg_temp.saife_wd((CURRENT_DATE - 182)), 2.0, '줄걸이 용구와 훅 해지장치 점검, 신호수 배치와 출입 통제선 설치, 인양, 착지 확인 후 줄걸이 해체', '인양 반경 출입 통제, 신호는 신호수 1명', '작업: 제관 구조물 인양 (1.5톤) / 공장동 1층 제관구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 182)), 'YYYY-MM-DD') || chr(10) || '작업자: 정민준 용접반장, 서하준 주임, 한도윤 사원' || chr(10) || '대상 설비: 천장크레인 1호 (공장동 1층 제관구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 인양물이 떨어지거나 흔들려 사람에 맞을 수 있습니다' || chr(10) || '2. 훅 해지장치나 슬링이 손상되면 줄걸이가 빠질 수 있습니다' || chr(10) || '3. 인양물 아래로 들어가면 피할 곳이 없습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 줄걸이 용구와 훅 해지장치를 확인하고 인양합니다' || chr(10) || '2. 신호수 한 명이 신호하고 인양물 아래 출입을 막습니다' || chr(10) || '3. 안전모, 안전화를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 182)) + TIME '07:56') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '정민준', ((pg_temp.saife_wd((CURRENT_DATE - 182)) + TIME '07:46') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 182)) + TIME '10:28') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 182))) + TIME '14:03') AT TIME ZONE 'Asia/Seoul')),
  (16, 1, 4, 20, '2층 벽면 배선 정리', '공장동 2층 조립구역', pg_temp.saife_wd((CURRENT_DATE - 170)), 3.0, '말비계 설치와 보조부재 체결, 배선 정리, 말비계 해체', '말비계 위 자재는 당일 사용량만', '작업: 2층 벽면 배선 정리 / 공장동 2층 조립구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 170)), 'YYYY-MM-DD') || chr(10) || '작업자: 박민수 설비팀장, 강태호 기사, 장우진 사원' || chr(10) || '대상 설비: 말비계 1호 (공장동 2층 조립구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 높이 2.2m 작업입니다. 떨어지면 크게 다칩니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 보조부재를 걸고 평평한 바닥에 세웁니다' || chr(10) || '2. 안전모를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 170)) + TIME '08:38') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '박민수', ((pg_temp.saife_wd((CURRENT_DATE - 170)) + TIME '07:33') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 170)) + TIME '12:02') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 170))) + TIME '14:27') AT TIME ZONE 'Asia/Seoul')),
  (17, 1, 3, 5, '원자재 입고 하역', '창고동 1층', pg_temp.saife_wd((CURRENT_DATE - 140)), 2.0, '운행 경로와 보행 통로 확인, 유도자 배치, 하역, 적재 높이 확인, 포크 내리고 주차', '보행자는 구획 통로로, 후진 시 유도자 신호', '작업: 원자재 입고 하역 / 창고동 1층 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 140)), 'YYYY-MM-DD') || chr(10) || '작업자: 최동훈 창고반장, 오지훈 주임, 윤서연 사원' || chr(10) || '대상 설비: 전동 지게차 1호 (창고동 1층)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 지게차 후진 중 보행자와 부딪힐 수 있습니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 보행자는 구획된 통로로 다니고 유도자가 신호합니다' || chr(10) || '2. 안전모, 안전화를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 140)) + TIME '08:36') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '최동훈', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 140))) + TIME '16:51') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 140)) + TIME '10:53') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 140))) + TIME '13:22') AT TIME ZONE 'Asia/Seoul')),
  (18, 1, 2, 8, 'CNC 선반 2호 척 교체', '공장동 1층 가공구역', pg_temp.saife_wd((CURRENT_DATE - 128)), 3.0, '전원 차단과 잠금, 척 교체, 방호덮개 닫고 시운전', '정비 중 표지 부착, 전원 잠금 열쇠는 작업자 휴대', '작업: CNC 선반 2호 척 교체 / 공장동 1층 가공구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 128)), 'YYYY-MM-DD') || chr(10) || '작업자: 이영희 가공반장, 장우진 사원' || chr(10) || '대상 설비: CNC 선반 2호 (공장동 1층 가공구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 회전부에 손이나 옷이 말려 들어갈 수 있습니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 정비 전에 전원을 끄고 잠급니다' || chr(10) || '2. 작업 후 덮개를 다시 고정합니다' || chr(10) || '3. 작업에 맞는 보호구를 갖추고 시작합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 128)) + TIME '08:19') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '이영희', ((pg_temp.saife_wd((CURRENT_DATE - 128)) + TIME '07:53') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 128)) + TIME '11:36') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 128))) + TIME '13:51') AT TIME ZONE 'Asia/Seoul')),
  (19, 1, 5, 16, '금형 인양 (1.2톤)', '공장동 1층 제관구역', pg_temp.saife_wd((CURRENT_DATE - 120)), 2.0, '줄걸이 용구와 훅 해지장치 점검, 신호수 배치와 출입 통제선 설치, 인양, 착지 확인 후 줄걸이 해체', '인양 반경 출입 통제, 신호는 신호수 1명', '작업: 금형 인양 (1.2톤) / 공장동 1층 제관구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 120)), 'YYYY-MM-DD') || chr(10) || '작업자: 정민준 용접반장, 서하준 주임, 한도윤 사원' || chr(10) || '대상 설비: 천장크레인 1호 (공장동 1층 제관구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 인양물이 떨어지거나 흔들려 사람에 맞을 수 있습니다' || chr(10) || '2. 훅 해지장치나 슬링이 손상되면 줄걸이가 빠질 수 있습니다' || chr(10) || '3. 인양물 아래로 들어가면 피할 곳이 없습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 줄걸이 용구와 훅 해지장치를 확인하고 인양합니다' || chr(10) || '2. 신호수 한 명이 신호하고 인양물 아래 출입을 막습니다' || chr(10) || '3. 안전모, 안전화를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 120)) + TIME '08:30') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '정민준', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 120))) + TIME '15:08') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 120)) + TIME '10:49') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 120))) + TIME '13:15') AT TIME ZONE 'Asia/Seoul')),
  (20, 1, 1, 2, '도장 부스 덕트 청소', '공장동 후면 차양부', pg_temp.saife_wd((CURRENT_DATE - 112)), 3.0, '배기 팬 정지, 덕트 분해와 청소, 조립, 배기 가동 확인', '작업 중 배기 팬 정지 금지', '작업: 도장 부스 덕트 청소 / 공장동 후면 차양부 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 112)), 'YYYY-MM-DD') || chr(10) || '작업자: 김철수 생산반장, 강태호 기사' || chr(10) || '대상 설비: 도장 부스 1호 (공장동 후면 차양부)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 우레탄 도료 증기는 불이 잘 붙고, 들이마시면 어지러울 수 있습니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 창과 문을 열어 환기하고, 주변에 불씨를 두지 않습니다' || chr(10) || '2. 방독마스크를 착용합니다' || chr(10) || '' || chr(10) || '화학물질: 우레탄 도료, 추정 주성분 톨루엔, 제품 MSDS 확인 필요, 유해성 H225 고인화성 액체 및 증기' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 112)) + TIME '08:27') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '김철수', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 112))) + TIME '15:38') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 112)) + TIME '11:52') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 112))) + TIME '14:52') AT TIME ZONE 'Asia/Seoul')),
  (21, 1, 7, 24, '지붕 채광창 주변 방수 보수', '공장동 옥상', pg_temp.saife_wd((CURRENT_DATE - 100)), 5.0, '채광창 임시 덮개 설치, 구명줄에 안전대 체결, 방수 보수, 하강', '강풍, 강우 시 작업 중지', '작업: 지붕 채광창 주변 방수 보수 / 공장동 옥상 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 100)), 'YYYY-MM-DD') || chr(10) || '작업자: 박민수 설비팀장, 강태호 기사' || chr(10) || '대상 설비: 지붕 작업 구역 (공장동 옥상)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 높이 6m 지붕 작업입니다. 떨어지면 크게 다칩니다' || chr(10) || '2. 채광창은 사람 무게를 버티지 못합니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 안전대를 구명줄에 걸고 작업합니다' || chr(10) || '2. 채광창 위로 올라서지 않습니다' || chr(10) || '3. 안전모, 안전대를 착용합니다' || chr(10) || '미이행 조치: 지붕 채광창 덮개와 추락방호망 설치 (기한 ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 45)), 'YYYY-MM-DD') || ')' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 100)) + TIME '08:26') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', '채광창 위 합판 임시 덮개, 안전대 상시 체결', '박민수', ((pg_temp.saife_wd((CURRENT_DATE - 100)) + TIME '07:33') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 100)) + TIME '14:51') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 100))) + TIME '14:53') AT TIME ZONE 'Asia/Seoul')),
  (22, 1, 4, 19, '2층 조명 배선 점검', '공장동 2층 조립구역', pg_temp.saife_wd((CURRENT_DATE - 92)), 3.0, '비계 설치와 바퀴 고정, 점검, 비계 해체', '비계 위 자재는 당일 사용량만', '작업: 2층 조명 배선 점검 / 공장동 2층 조립구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 92)), 'YYYY-MM-DD') || chr(10) || '작업자: 박민수 설비팀장, 강태호 기사' || chr(10) || '대상 설비: 이동식 비계 1호 (공장동 2층 조립구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 높이 3.2m 작업입니다. 떨어지면 크게 다칩니다' || chr(10) || '2. 바퀴가 고정되지 않으면 비계가 움직여 떨어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 바퀴 브레이크와 안전난간을 확인하고 올라갑니다' || chr(10) || '2. 안전모를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 92)) + TIME '08:09') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '박민수', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 92))) + TIME '15:13') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 92)) + TIME '11:27') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 92))) + TIME '13:28') AT TIME ZONE 'Asia/Seoul')),
  (23, 1, 3, 17, '완제품 출하 상차', '창고동 1층', pg_temp.saife_wd((CURRENT_DATE - 85)), 3.0, '운행 경로와 보행 통로 확인, 유도자 배치, 하역, 적재 높이 확인, 포크 내리고 주차', '보행자는 구획 통로로, 후진 시 유도자 신호', '작업: 완제품 출하 상차 / 창고동 1층 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 85)), 'YYYY-MM-DD') || chr(10) || '작업자: 최동훈 창고반장, 오지훈 주임, 윤서연 사원' || chr(10) || '대상 설비: 전동 지게차 2호 (창고동 1층)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 지게차 후진 중 보행자와 부딪힐 수 있습니다' || chr(10) || '2. 적재 높이를 넘기면 화물이 떨어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 보행자는 구획된 통로로 다니고 유도자가 신호합니다' || chr(10) || '2. 포크를 내리고 이동하며 정해진 적재 높이를 넘기지 않습니다' || chr(10) || '3. 안전모, 안전화를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 85)) + TIME '08:28') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '최동훈', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 85))) + TIME '15:43') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 85)) + TIME '12:08') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 85))) + TIME '13:11') AT TIME ZONE 'Asia/Seoul')),
  (24, 1, 2, 11, '공기압축기 드레인 밸브 교체', '공장동 1층 가공구역', pg_temp.saife_wd((CURRENT_DATE - 78)), 2.0, '전원 차단과 잠금, 잔압 배출, 밸브 교체, 시운전', '정비 중 표지 부착, 전원 잠금 열쇠는 작업자 휴대', '작업: 공기압축기 드레인 밸브 교체 / 공장동 1층 가공구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 78)), 'YYYY-MM-DD') || chr(10) || '작업자: 박민수 설비팀장, 강태호 기사' || chr(10) || '대상 설비: 공기압축기 1호 (공장동 1층 가공구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 회전부에 손이나 옷이 말려 들어갈 수 있습니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 정비 전에 전원을 끄고 잠급니다' || chr(10) || '2. 작업 후 덮개를 다시 고정합니다' || chr(10) || '3. 작업에 맞는 보호구를 갖추고 시작합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 78)) + TIME '08:22') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '박민수', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 78))) + TIME '16:42') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 78)) + TIME '10:46') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 78))) + TIME '14:35') AT TIME ZONE 'Asia/Seoul')),
  (25, 1, 5, 16, '제관 구조물 인양 (2톤)', '공장동 1층 제관구역', pg_temp.saife_wd((CURRENT_DATE - 70)), 2.0, '줄걸이 용구와 훅 해지장치 점검, 신호수 배치와 출입 통제선 설치, 인양, 착지 확인 후 줄걸이 해체', '인양 반경 출입 통제, 신호는 신호수 1명', '작업: 제관 구조물 인양 (2톤) / 공장동 1층 제관구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 70)), 'YYYY-MM-DD') || chr(10) || '작업자: 정민준 용접반장, 서하준 주임, 한도윤 사원' || chr(10) || '대상 설비: 천장크레인 1호 (공장동 1층 제관구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 인양물이 떨어지거나 흔들려 사람에 맞을 수 있습니다' || chr(10) || '2. 훅 해지장치나 슬링이 손상되면 줄걸이가 빠질 수 있습니다' || chr(10) || '3. 인양물 아래로 들어가면 피할 곳이 없습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 줄걸이 용구와 훅 해지장치를 확인하고 인양합니다' || chr(10) || '2. 신호수 한 명이 신호하고 인양물 아래 출입을 막습니다' || chr(10) || '3. 안전모, 안전화를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 70)) + TIME '08:18') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '정민준', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 70))) + TIME '16:33') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 70)) + TIME '10:40') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 70))) + TIME '14:11') AT TIME ZONE 'Asia/Seoul')),
  (26, 1, 6, 23, '혼합기 정기 청소', '공장동 후면 조색실', pg_temp.saife_wd((CURRENT_DATE - 64)), 2.0, '전원 차단과 잠금, 잔여 도료 배출, 날개 세척, 시운전', '작업 중 조색실 출입문 개방', '작업: 혼합기 정기 청소 / 공장동 후면 조색실 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 64)), 'YYYY-MM-DD') || chr(10) || '작업자: 김철수 생산반장, 강태호 기사' || chr(10) || '대상 설비: 페인트 혼합기 (공장동 후면 조색실)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 우레탄 도료 증기는 불이 잘 붙고, 들이마시면 어지러울 수 있습니다' || chr(10) || '2. 회전부에 손이나 옷이 말려 들어갈 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 창과 문을 열어 환기하고, 주변에 불씨를 두지 않습니다' || chr(10) || '2. 정비 전에 전원을 끄고 잠급니다' || chr(10) || '3. 방독마스크를 착용합니다' || chr(10) || '' || chr(10) || '화학물질: 우레탄 도료, 추정 주성분 톨루엔, 제품 MSDS 확인 필요, 유해성 H225 고인화성 액체 및 증기' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 64)) + TIME '08:40') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '김철수', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 64))) + TIME '16:29') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 64)) + TIME '11:02') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 64))) + TIME '15:06') AT TIME ZONE 'Asia/Seoul')),
  (27, 1, 3, 5, '원자재 입고 하역', '창고동 1층', pg_temp.saife_wd((CURRENT_DATE - 42)), 2.0, '운행 경로와 보행 통로 확인, 유도자 배치, 하역, 적재 높이 확인, 포크 내리고 주차', '보행자는 구획 통로로, 후진 시 유도자 신호', '작업: 원자재 입고 하역 / 창고동 1층 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 42)), 'YYYY-MM-DD') || chr(10) || '작업자: 최동훈 창고반장, 오지훈 주임, 윤서연 사원' || chr(10) || '대상 설비: 전동 지게차 1호 (창고동 1층)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 지게차 후진 중 보행자와 부딪힐 수 있습니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 보행자는 구획된 통로로 다니고 유도자가 신호합니다' || chr(10) || '2. 안전모, 안전화를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 42)) + TIME '08:25') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '최동훈', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 42))) + TIME '15:42') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 42)) + TIME '11:05') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 42))) + TIME '14:03') AT TIME ZONE 'Asia/Seoul')),
  (28, 1, 2, 8, 'CNC 선반 2호 절삭유 교체', '공장동 1층 가공구역', pg_temp.saife_wd((CURRENT_DATE - 35)), 2.0, '전원 차단과 잠금, 절삭유 배출, 탱크 청소, 주입', '정비 중 표지 부착, 전원 잠금 열쇠는 작업자 휴대', '작업: CNC 선반 2호 절삭유 교체 / 공장동 1층 가공구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 35)), 'YYYY-MM-DD') || chr(10) || '작업자: 이영희 가공반장, 장우진 사원' || chr(10) || '대상 설비: CNC 선반 2호 (공장동 1층 가공구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 회전부에 손이나 옷이 말려 들어갈 수 있습니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 정비 전에 전원을 끄고 잠급니다' || chr(10) || '2. 작업 후 덮개를 다시 고정합니다' || chr(10) || '3. 작업에 맞는 보호구를 갖추고 시작합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 35)) + TIME '08:19') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '이영희', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 35))) + TIME '15:44') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 35)) + TIME '10:48') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 35))) + TIME '14:16') AT TIME ZONE 'Asia/Seoul')),
  (29, 1, 4, 20, '2층 벽면 안내판 설치', '공장동 2층 조립구역', pg_temp.saife_wd((CURRENT_DATE - 27)), 2.0, '말비계 설치와 보조부재 체결, 안내판 고정, 말비계 해체', '말비계 위 자재는 당일 사용량만', '작업: 2층 벽면 안내판 설치 / 공장동 2층 조립구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 27)), 'YYYY-MM-DD') || chr(10) || '작업자: 박민수 설비팀장, 강태호 기사, 장우진 사원' || chr(10) || '대상 설비: 말비계 1호 (공장동 2층 조립구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 높이 2.2m 작업입니다. 떨어지면 크게 다칩니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 보조부재를 걸고 평평한 바닥에 세웁니다' || chr(10) || '2. 안전모를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 27)) + TIME '08:04') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '박민수', ((pg_temp.saife_wd((CURRENT_DATE - 27)) + TIME '07:44') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 27)) + TIME '10:29') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 27))) + TIME '13:11') AT TIME ZONE 'Asia/Seoul')),
  (30, 1, 3, 17, '코일 입고 하역', '창고동 1층', pg_temp.saife_wd((CURRENT_DATE - 14)), 2.0, '운행 경로와 보행 통로 확인, 유도자 배치, 하역, 적재 높이 확인, 포크 내리고 주차', '보행자는 구획 통로로, 후진 시 유도자 신호', '작업: 코일 입고 하역 / 창고동 1층 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 14)), 'YYYY-MM-DD') || chr(10) || '작업자: 최동훈 창고반장, 오지훈 주임, 윤서연 사원' || chr(10) || '대상 설비: 전동 지게차 2호 (창고동 1층)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 지게차 후진 중 보행자와 부딪힐 수 있습니다' || chr(10) || '2. 적재 높이를 넘기면 화물이 떨어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 보행자는 구획된 통로로 다니고 유도자가 신호합니다' || chr(10) || '2. 포크를 내리고 이동하며 정해진 적재 높이를 넘기지 않습니다' || chr(10) || '3. 안전모, 안전화를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 14)) + TIME '08:35') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '최동훈', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 14))) + TIME '15:40') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 14)) + TIME '11:13') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 14))) + TIME '15:00') AT TIME ZONE 'Asia/Seoul')),
  (31, 1, 1, 2, '부품 하도 도장', '공장동 후면 차양부', pg_temp.saife_wd((CURRENT_DATE - 8)), 6.0, '부품 거치, 배기 가동 확인, 하도 도장, 건조', '작업 중 배기 팬 정지 금지', '작업: 부품 하도 도장 / 공장동 후면 차양부 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 8)), 'YYYY-MM-DD') || chr(10) || '작업자: 김철수 생산반장, 강태호 기사' || chr(10) || '대상 설비: 도장 부스 1호 (공장동 후면 차양부)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 우레탄 도료 증기는 불이 잘 붙고, 들이마시면 어지러울 수 있습니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 창과 문을 열어 환기하고, 주변에 불씨를 두지 않습니다' || chr(10) || '2. 방독마스크를 착용합니다' || chr(10) || '' || chr(10) || '화학물질: 우레탄 도료, 추정 주성분 톨루엔, 제품 MSDS 확인 필요, 유해성 H225 고인화성 액체 및 증기' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 8)) + TIME '08:16') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '김철수', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 8))) + TIME '16:52') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 8)) + TIME '15:34') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 8))) + TIME '13:01') AT TIME ZONE 'Asia/Seoul')),
  (32, 1, 2, 4, '유압 프레스 3호 금형 교체', '공장동 1층 가공구역', pg_temp.saife_wd((CURRENT_DATE - 6)), 3.0, '전원 차단과 잠금, 안전블록 설치, 금형 교체, 시운전', '금형 교체 중 기동 스위치 잠금, 열쇠는 작업자 휴대', '작업: 유압 프레스 3호 금형 교체 / 공장동 1층 가공구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 6)), 'YYYY-MM-DD') || chr(10) || '작업자: 이영희 가공반장, 장우진 사원' || chr(10) || '대상 설비: 유압 프레스 3호 (공장동 1층 가공구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 금형 사이에 손이 들어가면 끼일 수 있습니다' || chr(10) || '2. 방호장치를 끄거나 떼고 작업하면 손이 위험한계에 들어갑니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 금형 교체 전에 전원을 끄고 잠급니다' || chr(10) || '2. 안전블록을 끼우고 작업합니다' || chr(10) || '3. 작업에 맞는 보호구를 갖추고 시작합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 6)) + TIME '08:35') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '이영희', ((pg_temp.saife_wd((CURRENT_DATE - 6)) + TIME '08:08') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 6)) + TIME '12:13') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 6))) + TIME '14:42') AT TIME ZONE 'Asia/Seoul')),
  (33, 1, 4, 19, '2층 덕트 보온재 보수', '공장동 2층 조립구역', pg_temp.saife_wd((CURRENT_DATE - 3)), 4.0, '비계 설치와 바퀴 고정, 보온재 교체, 비계 해체', '비계 위 자재는 당일 사용량만', '작업: 2층 덕트 보온재 보수 / 공장동 2층 조립구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 3)), 'YYYY-MM-DD') || chr(10) || '작업자: 박민수 설비팀장, 강태호 기사' || chr(10) || '대상 설비: 이동식 비계 1호 (공장동 2층 조립구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 높이 3.4m 작업입니다. 떨어지면 크게 다칩니다' || chr(10) || '2. 바퀴가 고정되지 않으면 비계가 움직여 떨어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 바퀴 브레이크와 안전난간을 확인하고 올라갑니다' || chr(10) || '2. 안전모를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 3)) + TIME '08:09') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '박민수', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 3))) + TIME '16:07') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 3)) + TIME '13:27') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 3))) + TIME '14:12') AT TIME ZONE 'Asia/Seoul')),
  (34, 1, 6, 23, '도료 조색 혼합', '공장동 후면 조색실', pg_temp.saife_wd((CURRENT_DATE - 1)), 4.0, '덮개 닫힘 확인, 원료 투입, 혼합, 용기 밀폐', '작업 중 조색실 출입문 개방', '작업: 도료 조색 혼합 / 공장동 후면 조색실 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 1)), 'YYYY-MM-DD') || chr(10) || '작업자: 김철수 생산반장, 강태호 기사' || chr(10) || '대상 설비: 페인트 혼합기 (공장동 후면 조색실)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 우레탄 도료 증기는 불이 잘 붙고, 들이마시면 어지러울 수 있습니다' || chr(10) || '2. 회전부에 손이나 옷이 말려 들어갈 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 창과 문을 열어 환기하고, 주변에 불씨를 두지 않습니다' || chr(10) || '2. 정비 전에 전원을 끄고 잠급니다' || chr(10) || '3. 방독마스크를 착용합니다' || chr(10) || '' || chr(10) || '화학물질: 우레탄 도료, 추정 주성분 톨루엔, 제품 MSDS 확인 필요, 유해성 H225 고인화성 액체 및 증기' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 1)) + TIME '08:29') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '김철수', ((pg_temp.saife_wd((CURRENT_DATE - 1)) + TIME '07:46') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 1)) + TIME '13:54') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 1))) + TIME '14:02') AT TIME ZONE 'Asia/Seoul')),
  (35, 1, 5, 13, '용접구역 작업대 보강 용접', '공장동 1층 제관구역', pg_temp.saife_wd((CURRENT_DATE - 44)), 5.0, '가연물 정리와 방화포 설치, 화재감시자 배치, 용접, 잔불 확인', '용접 종료 후 30분 잔불 확인', '작업: 용접구역 작업대 보강 용접 / 공장동 1층 제관구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 44)), 'YYYY-MM-DD') || chr(10) || '작업자: 정민준 용접반장, 장우진 사원' || chr(10) || '대상 설비: CO2 용접기 1호 (공장동 1층 제관구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 보안면 없이 아크 빛을 보면 눈을 다칠 수 있습니다' || chr(10) || '2. 불티가 튀어 주변 가연물에 불이 붙을 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 반경 안의 가연물을 치우고 방화포를 덮습니다' || chr(10) || '2. 화재감시자를 두고 소화기를 옆에 둡니다' || chr(10) || '3. 보안면, 용접용 장갑을 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 44)) + TIME '08:20') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '정민준', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 44))) + TIME '15:50') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 44)) + TIME '14:47') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 44))) + TIME '13:09') AT TIME ZONE 'Asia/Seoul')),
  (36, 1, 5, 14, '용접 2번 부스 지그 수리', '공장동 1층 제관구역', pg_temp.saife_wd((CURRENT_DATE - 96)), 4.0, '가연물 정리와 방화포 설치, 화재감시자 배치, 용접, 잔불 확인', '용접 종료 후 30분 잔불 확인', '작업: 용접 2번 부스 지그 수리 / 공장동 1층 제관구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 96)), 'YYYY-MM-DD') || chr(10) || '작업자: 정민준 용접반장, 강태호 기사' || chr(10) || '대상 설비: CO2 용접기 2호 (공장동 1층 제관구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 불티가 튀어 주변 가연물에 불이 붙을 수 있습니다' || chr(10) || '2. 보안면 없이 아크 빛을 보면 눈을 다칠 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 반경 안의 가연물을 치우고 방화포를 덮습니다' || chr(10) || '2. 화재감시자를 두고 소화기를 옆에 둡니다' || chr(10) || '3. 보안면, 용접용 장갑을 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 96)) + TIME '08:02') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', NULL, '정민준', ((pg_temp.saife_wd((CURRENT_DATE - 96)) + TIME '07:46') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 96)) + TIME '13:20') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 96))) + TIME '14:16') AT TIME ZONE 'Asia/Seoul')),
  (37, 1, 5, 16, '금형 인양 (1.2톤)', '공장동 1층 제관구역', pg_temp.saife_wd((CURRENT_DATE - 20)), 2.0, '줄걸이 용구와 훅 해지장치 점검, 신호수 배치와 출입 통제선 설치, 인양, 착지 확인 후 줄걸이 해체', '인양 반경 출입 통제, 신호는 신호수 1명', '작업: 금형 인양 (1.2톤) / 공장동 1층 제관구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 20)), 'YYYY-MM-DD') || chr(10) || '작업자: 정민준 용접반장, 서하준 주임, 한도윤 사원' || chr(10) || '대상 설비: 천장크레인 1호 (공장동 1층 제관구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 인양물이 떨어지거나 흔들려 사람에 맞을 수 있습니다' || chr(10) || '2. 훅 해지장치나 슬링이 손상되면 줄걸이가 빠질 수 있습니다' || chr(10) || '3. 인양물 아래로 들어가면 피할 곳이 없습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 줄걸이 용구와 훅 해지장치를 확인하고 인양합니다' || chr(10) || '2. 신호수 한 명이 신호하고 인양물 아래 출입을 막습니다' || chr(10) || '3. 안전모, 안전화를 착용합니다' || chr(10) || '미이행 조치: 천장크레인 훅 해지장치 교체 (기한 ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 28)), 'YYYY-MM-DD') || ')' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', ((pg_temp.saife_wd((CURRENT_DATE - 20)) + TIME '08:27') AT TIME ZONE 'Asia/Seoul'), 'CLOSED', '훅 해지장치 교체 전까지 신호수가 줄걸이 상태를 확인한 뒤 인양', '정민준', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 20))) + TIME '15:37') AT TIME ZONE 'Asia/Seoul'), ((pg_temp.saife_wd((CURRENT_DATE - 20)) + TIME '11:50') AT TIME ZONE 'Asia/Seoul'), NULL, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 20))) + TIME '14:57') AT TIME ZONE 'Asia/Seoul')),
  (38, 1, 3, 17, '코일 입고 하역', '창고동 1층', pg_temp.saife_wd((CURRENT_DATE - 0)), 3.0, '운행 경로와 보행 통로 확인, 유도자 배치, 하역, 적재 높이 확인, 포크 내리고 주차', '보행자는 구획 통로로, 후진 시 유도자 신호', '작업: 코일 입고 하역 / 창고동 1층 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 0)), 'YYYY-MM-DD') || chr(10) || '작업자: 최동훈 창고반장, 오지훈 주임, 윤서연 사원' || chr(10) || '대상 설비: 전동 지게차 2호 (창고동 1층)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 지게차 후진 중 보행자와 부딪힐 수 있습니다' || chr(10) || '2. 적재 높이를 넘기면 화물이 떨어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 보행자는 구획된 통로로 다니고 유도자가 신호합니다' || chr(10) || '2. 포크를 내리고 이동하며 정해진 적재 높이를 넘기지 않습니다' || chr(10) || '3. 안전모, 안전화를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', NULL, 'SUBMITTED', NULL, NULL, NULL, NULL, NULL, ((pg_temp.saife_wd((CURRENT_DATE - 1)) + TIME '13:33') AT TIME ZONE 'Asia/Seoul')),
  (39, 1, 4, 19, '2층 조립구역 배관 보온 작업', '공장동 2층 조립구역', pg_temp.saife_wd((CURRENT_DATE + 1)), 6.0, '비계 설치와 바퀴 고정, 안전난간 확인, 보온재 시공, 비계 해체', '비계 위 자재는 당일 사용량만', '작업: 2층 조립구역 배관 보온 작업 / 공장동 2층 조립구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE + 1)), 'YYYY-MM-DD') || chr(10) || '작업자: 박민수 설비팀장, 강태호 기사' || chr(10) || '대상 설비: 이동식 비계 1호 (공장동 2층 조립구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 높이 3.6m 작업입니다. 떨어지면 크게 다칩니다' || chr(10) || '2. 바퀴가 고정되지 않으면 비계가 움직여 떨어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 바퀴 브레이크와 안전난간을 확인하고 올라갑니다' || chr(10) || '2. 안전모를 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', NULL, 'SUBMITTED', NULL, NULL, NULL, NULL, NULL, ((pg_temp.saife_wd((CURRENT_DATE - 1)) + TIME '13:44') AT TIME ZONE 'Asia/Seoul')),
  (40, 1, 2, 8, 'CNC 선반 2호 척 교체', '공장동 1층 가공구역', pg_temp.saife_wd((CURRENT_DATE + 2)), 3.0, '전원 차단과 잠금, 척 교체, 방호덮개 닫고 시운전', '정비 중 표지 부착, 전원 잠금 열쇠는 작업자 휴대', '작업: CNC 선반 2호 척 교체 / 공장동 1층 가공구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE + 2)), 'YYYY-MM-DD') || chr(10) || '작업자: 이영희 가공반장, 장우진 사원' || chr(10) || '대상 설비: CNC 선반 2호 (공장동 1층 가공구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 회전부에 손이나 옷이 말려 들어갈 수 있습니다' || chr(10) || '2. 작업 구역이 정리되지 않으면 걸려 넘어질 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 정비 전에 전원을 끄고 잠급니다' || chr(10) || '2. 작업 후 덮개를 다시 고정합니다' || chr(10) || '3. 작업에 맞는 보호구를 갖추고 시작합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', NULL, 'APPROVED', NULL, '이영희', ((pg_temp.saife_wd((CURRENT_DATE - 1)) + TIME '15:42') AT TIME ZONE 'Asia/Seoul'), NULL, NULL, ((pg_temp.saife_wd((CURRENT_DATE - 1)) + TIME '13:05') AT TIME ZONE 'Asia/Seoul')),
  (41, 1, 5, 14, '용접 2번 부스 브래킷 용접', '공장동 1층 제관구역', pg_temp.saife_wd((CURRENT_DATE + 4)), 5.0, '가연물 정리와 방화포 설치, 화재감시자 배치, 용접, 잔불 확인', '용접 종료 후 30분 잔불 확인', '작업: 용접 2번 부스 브래킷 용접 / 공장동 1층 제관구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE + 4)), 'YYYY-MM-DD') || chr(10) || '작업자: 정민준 용접반장, 강태호 기사' || chr(10) || '대상 설비: CO2 용접기 2호 (공장동 1층 제관구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 불티가 튀어 주변 가연물에 불이 붙을 수 있습니다' || chr(10) || '2. 보안면 없이 아크 빛을 보면 눈을 다칠 수 있습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 반경 안의 가연물을 치우고 방화포를 덮습니다' || chr(10) || '2. 화재감시자를 두고 소화기를 옆에 둡니다' || chr(10) || '3. 보안면, 용접용 장갑을 착용합니다' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', NULL, 'APPROVED', NULL, '정민준', ((pg_temp.saife_wd((CURRENT_DATE - 1)) + TIME '15:26') AT TIME ZONE 'Asia/Seoul'), NULL, NULL, ((pg_temp.saife_wd((CURRENT_DATE - 1)) + TIME '14:46') AT TIME ZONE 'Asia/Seoul')),
  (42, 1, 5, 16, '금형 인양 (1.2톤)', '공장동 1층 제관구역', pg_temp.saife_wd((CURRENT_DATE + 1)), 2.0, '줄걸이 용구와 훅 해지장치 점검, 신호수 배치와 출입 통제선 설치, 인양, 착지 확인 후 줄걸이 해체', '인양 반경 출입 통제, 신호는 신호수 1명', '작업: 금형 인양 (1.2톤) / 공장동 1층 제관구역 / ' || to_char(pg_temp.saife_wd((CURRENT_DATE + 1)), 'YYYY-MM-DD') || chr(10) || '작업자: 정민준 용접반장, 서하준 주임, 한도윤 사원' || chr(10) || '대상 설비: 천장크레인 1호 (공장동 1층 제관구역)' || chr(10) || '' || chr(10) || '위험 포인트' || chr(10) || '1. 인양물이 떨어지거나 흔들려 사람에 맞을 수 있습니다' || chr(10) || '2. 훅 해지장치나 슬링이 손상되면 줄걸이가 빠질 수 있습니다' || chr(10) || '3. 인양물 아래로 들어가면 피할 곳이 없습니다' || chr(10) || '' || chr(10) || '지킬 것' || chr(10) || '1. 줄걸이 용구와 훅 해지장치를 확인하고 인양합니다' || chr(10) || '2. 신호수 한 명이 신호하고 인양물 아래 출입을 막습니다' || chr(10) || '3. 안전모, 안전화를 착용합니다' || chr(10) || '미이행 조치: 천장크레인 훅 해지장치 교체 (기한 ' || to_char(pg_temp.saife_wd((CURRENT_DATE - 28)), 'YYYY-MM-DD') || ')' || chr(10) || '' || chr(10) || '위험하면 작업을 멈추고 관리감독자에게 알립니다.', NULL, 'HOLD', '훅 해지장치 교체 전까지 신호수가 줄걸이 상태를 확인한 뒤 인양', '정민준', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 20))) + TIME '15:49') AT TIME ZONE 'Asia/Seoul'), NULL, '작업 보류: 수시평가 완료 전 작업 재개 금지', ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 20))) + TIME '13:34') AT TIME ZONE 'Asia/Seoul'));
SELECT setval('work_plan_id_seq', 42, true);
INSERT INTO work_plan_worker (work_plan_id, name, position, duty) VALUES
  (1, '박민수', '설비팀장', '관리감독자'),
  (1, '이도현', '기사', '작업'),
  (2, '박민수', '설비팀장', '관리감독자'),
  (2, '강태호', '기사', '작업'),
  (3, '정민준', '용접반장', '작업지휘자'),
  (3, '서하준', '주임', '신호수'),
  (3, '한도윤', '사원', '줄걸이'),
  (4, '최동훈', '창고반장', '작업지휘자'),
  (4, '오지훈', '주임', '지게차 운전'),
  (4, '윤서연', '사원', '유도자'),
  (5, '김철수', '생산반장', '관리감독자'),
  (5, '장우진', '사원', '작업'),
  (6, '이영희', '가공반장', '관리감독자'),
  (6, '장우진', '사원', '작업'),
  (7, '박민수', '설비팀장', '관리감독자'),
  (7, '강태호', '기사', '작업'),
  (8, '정민준', '용접반장', '작업지휘자'),
  (8, '서하준', '주임', '신호수'),
  (8, '한도윤', '사원', '줄걸이'),
  (9, '최동훈', '창고반장', '작업지휘자'),
  (9, '오지훈', '주임', '지게차 운전'),
  (9, '윤서연', '사원', '유도자'),
  (10, '이영희', '가공반장', '관리감독자'),
  (10, '장우진', '사원', '작업'),
  (11, '이영희', '가공반장', '관리감독자'),
  (11, '장우진', '사원', '작업'),
  (12, '김철수', '생산반장', '관리감독자'),
  (12, '강태호', '기사', '작업'),
  (13, '박민수', '설비팀장', '관리감독자'),
  (13, '강태호', '기사', '작업'),
  (14, '박민수', '설비팀장', '관리감독자'),
  (14, '장우진', '사원', '작업'),
  (15, '정민준', '용접반장', '작업지휘자'),
  (15, '서하준', '주임', '신호수'),
  (15, '한도윤', '사원', '줄걸이'),
  (16, '박민수', '설비팀장', '관리감독자'),
  (16, '강태호', '기사', '작업'),
  (16, '장우진', '사원', '작업'),
  (17, '최동훈', '창고반장', '작업지휘자'),
  (17, '오지훈', '주임', '지게차 운전'),
  (17, '윤서연', '사원', '유도자'),
  (18, '이영희', '가공반장', '관리감독자'),
  (18, '장우진', '사원', '작업'),
  (19, '정민준', '용접반장', '작업지휘자'),
  (19, '서하준', '주임', '신호수'),
  (19, '한도윤', '사원', '줄걸이'),
  (20, '김철수', '생산반장', '관리감독자'),
  (20, '강태호', '기사', '작업'),
  (21, '박민수', '설비팀장', '관리감독자'),
  (21, '강태호', '기사', '작업'),
  (22, '박민수', '설비팀장', '관리감독자'),
  (22, '강태호', '기사', '작업'),
  (23, '최동훈', '창고반장', '작업지휘자'),
  (23, '오지훈', '주임', '지게차 운전'),
  (23, '윤서연', '사원', '유도자'),
  (24, '박민수', '설비팀장', '관리감독자'),
  (24, '강태호', '기사', '작업'),
  (25, '정민준', '용접반장', '작업지휘자'),
  (25, '서하준', '주임', '신호수'),
  (25, '한도윤', '사원', '줄걸이'),
  (26, '김철수', '생산반장', '관리감독자'),
  (26, '강태호', '기사', '작업'),
  (27, '최동훈', '창고반장', '작업지휘자'),
  (27, '오지훈', '주임', '지게차 운전'),
  (27, '윤서연', '사원', '유도자'),
  (28, '이영희', '가공반장', '관리감독자'),
  (28, '장우진', '사원', '작업'),
  (29, '박민수', '설비팀장', '관리감독자'),
  (29, '강태호', '기사', '작업'),
  (29, '장우진', '사원', '작업'),
  (30, '최동훈', '창고반장', '작업지휘자'),
  (30, '오지훈', '주임', '지게차 운전'),
  (30, '윤서연', '사원', '유도자'),
  (31, '김철수', '생산반장', '관리감독자'),
  (31, '강태호', '기사', '작업'),
  (32, '이영희', '가공반장', '관리감독자'),
  (32, '장우진', '사원', '작업'),
  (33, '박민수', '설비팀장', '관리감독자'),
  (33, '강태호', '기사', '작업'),
  (34, '김철수', '생산반장', '관리감독자'),
  (34, '강태호', '기사', '작업'),
  (35, '정민준', '용접반장', '관리감독자'),
  (35, '장우진', '사원', '작업'),
  (36, '정민준', '용접반장', '관리감독자'),
  (36, '강태호', '기사', '작업'),
  (37, '정민준', '용접반장', '작업지휘자'),
  (37, '서하준', '주임', '신호수'),
  (37, '한도윤', '사원', '줄걸이'),
  (38, '최동훈', '창고반장', '작업지휘자'),
  (38, '오지훈', '주임', '지게차 운전'),
  (38, '윤서연', '사원', '유도자'),
  (39, '박민수', '설비팀장', '관리감독자'),
  (39, '강태호', '기사', '작업'),
  (40, '이영희', '가공반장', '관리감독자'),
  (40, '장우진', '사원', '작업'),
  (41, '정민준', '용접반장', '관리감독자'),
  (41, '강태호', '기사', '작업'),
  (42, '정민준', '용접반장', '작업지휘자'),
  (42, '서하준', '주임', '신호수'),
  (42, '한도윤', '사원', '줄걸이');
INSERT INTO work_plan_slot (work_plan_id, slot_key, answered_value, ledger_value, conflicted, answered_at) VALUES
  (1, 'work_height', '2.4', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 45))) + TIME '13:19') AT TIME ZONE 'Asia/Seoul')),
  (1, 'platform_guardrail', '아니요', '결손', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 45))) + TIME '13:21') AT TIME ZONE 'Asia/Seoul')),
  (2, 'work_height', '6', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 355))) + TIME '13:49') AT TIME ZONE 'Asia/Seoul')),
  (2, 'anchor_installed', '아니요', '없음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 355))) + TIME '13:51') AT TIME ZONE 'Asia/Seoul')),
  (5, 'product_name', '우레탄 도료', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 318))) + TIME '13:46') AT TIME ZONE 'Asia/Seoul')),
  (6, 'guard_installed', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 305))) + TIME '15:08') AT TIME ZONE 'Asia/Seoul')),
  (7, 'guard_installed', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 290))) + TIME '14:09') AT TIME ZONE 'Asia/Seoul')),
  (10, 'guard_installed', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 248))) + TIME '13:27') AT TIME ZONE 'Asia/Seoul')),
  (11, 'guard_installed', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 240))) + TIME '13:32') AT TIME ZONE 'Asia/Seoul')),
  (12, 'guard_installed', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 225))) + TIME '15:13') AT TIME ZONE 'Asia/Seoul')),
  (12, 'product_name', '우레탄 도료', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 225))) + TIME '15:15') AT TIME ZONE 'Asia/Seoul')),
  (13, 'work_height', '6', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 210))) + TIME '13:06') AT TIME ZONE 'Asia/Seoul')),
  (13, 'anchor_installed', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 210))) + TIME '13:08') AT TIME ZONE 'Asia/Seoul')),
  (14, 'work_height', '3.6', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 196))) + TIME '14:15') AT TIME ZONE 'Asia/Seoul')),
  (14, 'platform_guardrail', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 196))) + TIME '14:17') AT TIME ZONE 'Asia/Seoul')),
  (14, 'caster_lock', '예', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 196))) + TIME '14:19') AT TIME ZONE 'Asia/Seoul')),
  (16, 'work_height', '2.2', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 170))) + TIME '14:30') AT TIME ZONE 'Asia/Seoul')),
  (18, 'guard_installed', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 128))) + TIME '13:54') AT TIME ZONE 'Asia/Seoul')),
  (20, 'product_name', '우레탄 도료', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 112))) + TIME '14:55') AT TIME ZONE 'Asia/Seoul')),
  (21, 'work_height', '6', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 100))) + TIME '14:56') AT TIME ZONE 'Asia/Seoul')),
  (21, 'anchor_installed', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 100))) + TIME '14:58') AT TIME ZONE 'Asia/Seoul')),
  (22, 'work_height', '3.2', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 92))) + TIME '13:31') AT TIME ZONE 'Asia/Seoul')),
  (22, 'platform_guardrail', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 92))) + TIME '13:33') AT TIME ZONE 'Asia/Seoul')),
  (22, 'caster_lock', '예', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 92))) + TIME '13:35') AT TIME ZONE 'Asia/Seoul')),
  (24, 'guard_installed', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 78))) + TIME '14:38') AT TIME ZONE 'Asia/Seoul')),
  (26, 'guard_installed', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 64))) + TIME '15:09') AT TIME ZONE 'Asia/Seoul')),
  (26, 'product_name', '우레탄 도료', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 64))) + TIME '15:11') AT TIME ZONE 'Asia/Seoul')),
  (28, 'guard_installed', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 35))) + TIME '14:19') AT TIME ZONE 'Asia/Seoul')),
  (29, 'work_height', '2.2', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 27))) + TIME '13:14') AT TIME ZONE 'Asia/Seoul')),
  (31, 'product_name', '우레탄 도료', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 8))) + TIME '13:04') AT TIME ZONE 'Asia/Seoul')),
  (32, 'guard_installed', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 6))) + TIME '14:45') AT TIME ZONE 'Asia/Seoul')),
  (33, 'work_height', '3.4', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 3))) + TIME '14:15') AT TIME ZONE 'Asia/Seoul')),
  (33, 'platform_guardrail', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 3))) + TIME '14:17') AT TIME ZONE 'Asia/Seoul')),
  (33, 'caster_lock', '예', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 3))) + TIME '14:19') AT TIME ZONE 'Asia/Seoul')),
  (34, 'guard_installed', '예', '있음', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 1))) + TIME '14:05') AT TIME ZONE 'Asia/Seoul')),
  (34, 'product_name', '우레탄 도료', '-', false, ((pg_temp.saife_prev(pg_temp.saife_wd((CURRENT_DATE - 1))) + TIME '14:07') AT TIME ZONE 'Asia/Seoul')),
  (39, 'work_height', '3.6', '-', false, ((pg_temp.saife_wd((CURRENT_DATE - 1)) + TIME '13:47') AT TIME ZONE 'Asia/Seoul')),
  (39, 'platform_guardrail', '예', '있음', false, ((pg_temp.saife_wd((CURRENT_DATE - 1)) + TIME '13:49') AT TIME ZONE 'Asia/Seoul')),
  (39, 'caster_lock', '예', '-', false, ((pg_temp.saife_wd((CURRENT_DATE - 1)) + TIME '13:51') AT TIME ZONE 'Asia/Seoul')),
  (40, 'guard_installed', '예', '있음', false, ((pg_temp.saife_wd((CURRENT_DATE - 1)) + TIME '13:08') AT TIME ZONE 'Asia/Seoul'));
INSERT INTO work_plan_hazard (work_plan_id, hazard_id) VALUES
  (1, 7),
  (2, 40),
  (3, 24),
  (3, 25),
  (4, 26),
  (5, 3),
  (5, 42),
  (6, 9),
  (7, 17),
  (8, 24),
  (8, 25),
  (9, 30),
  (10, 9),
  (11, 9),
  (12, 38),
  (12, 39),
  (13, 40),
  (14, 33),
  (15, 24),
  (15, 25),
  (16, 34),
  (17, 26),
  (18, 11),
  (18, 12),
  (19, 24),
  (19, 25),
  (20, 3),
  (20, 42),
  (21, 40),
  (21, 41),
  (22, 33),
  (23, 30),
  (24, 17),
  (25, 24),
  (25, 25),
  (26, 38),
  (26, 39),
  (27, 26),
  (28, 11),
  (28, 12),
  (29, 34),
  (30, 29),
  (30, 30),
  (31, 3),
  (31, 42),
  (32, 5),
  (33, 33),
  (34, 38),
  (34, 39),
  (35, 20),
  (35, 21),
  (36, 22),
  (37, 24),
  (37, 25),
  (37, 28),
  (38, 29),
  (38, 30),
  (39, 33),
  (40, 11),
  (40, 12),
  (41, 22),
  (42, 24),
  (42, 25),
  (42, 28);

-- ── 사고 ───────────────────────────────────────────────────────────
INSERT INTO incident (id, site_id, equipment_id, work_plan_id, occurred_at, victim_name, severity, leave_days, accident_type, description, cause, prevention, report_due_date, report_status, follow_up_assessment_id, created_at) VALUES
  (2, 1, 7, 11, ((pg_temp.saife_wd((CURRENT_DATE - 240)) + TIME '10:40') AT TIME ZONE 'Asia/Seoul'), '최OO', 'LOST_TIME', 2, 'CAUGHT', '금형 교체 후 시운전 중 소재 위치를 손으로 바로잡다가 왼손 검지 끝이 상, 하 금형 사이에 끼임', '불안전 상태: 양수조작 버튼이 금형 가까이 있어 한 손으로 조작할 수 있었음' || chr(10) || '불안전 행동: 시운전 중 소재 위치를 수공구 없이 손으로 바로잡음', '1. 시운전 중 소재 위치 조정은 수공구 사용, 양수조작 버튼 위치 재설정 (담당 가공반장 이영희, 기한 ' || to_char(GREATEST(pg_temp.saife_wd((pg_temp.saife_wd((CURRENT_DATE - 240)) + 14)), pg_temp.saife_next(pg_temp.saife_wd((CURRENT_DATE - 240)))), 'YYYY-MM-DD') || ')', NULL, 'NOT_REQUIRED', 20, ((pg_temp.saife_wd((CURRENT_DATE - 240)) + TIME '11:23') AT TIME ZONE 'Asia/Seoul')),
  (3, 1, 10, NULL, ((pg_temp.saife_wd((CURRENT_DATE - 115)) + TIME '14:10') AT TIME ZONE 'Asia/Seoul'), '장OO', 'LOST_TIME', 1, 'DROP', '탁상 연삭기로 공구를 연마하던 중 숫돌 파편이 튀어 오른쪽 눈 주위에 맞음', '불안전 상태: 숫돌 덮개 조정편과 숫돌 사이 간격이 벌어져 있었음' || chr(10) || '불안전 행동: 보안경을 쓰지 않고 연마함', '1. 숫돌 교체, 조정편 간격 재조정, 사용 전 1분 시운전 (담당 가공반장 이영희, 기한 ' || to_char(GREATEST(pg_temp.saife_wd((pg_temp.saife_wd((CURRENT_DATE - 115)) + 7)), pg_temp.saife_next(pg_temp.saife_wd((CURRENT_DATE - 115)))), 'YYYY-MM-DD') || ')' || chr(10) || '2. 연삭기 투명 비산 방지판 설치 (담당 설비팀장 박민수, 기한 ' || to_char(GREATEST(pg_temp.saife_wd((pg_temp.saife_wd((CURRENT_DATE - 115)) + 14)), pg_temp.saife_next(pg_temp.saife_wd((CURRENT_DATE - 115)))), 'YYYY-MM-DD') || ')', NULL, 'NOT_REQUIRED', 21, ((pg_temp.saife_wd((CURRENT_DATE - 115)) + TIME '15:37') AT TIME ZONE 'Asia/Seoul')),
  (4, 1, 17, NULL, ((pg_temp.saife_wd((CURRENT_DATE - 60)) + TIME '16:30') AT TIME ZONE 'Asia/Seoul'), NULL, 'NEAR_MISS', 0, 'STRUCK', '창고동 출입구에서 지게차가 후진하던 중 보행 작업자와 약 1m 거리까지 접근, 접촉 없음', '불안전 상태: 후진 경보기가 작동하지 않았고, 출입구 보행 통로가 바닥에 구획되어 있지 않았음' || chr(10) || '불안전 행동: 운전원이 후방을 확인하지 않고 후진함', '1. 지게차 후진 경보기, 후방 카메라 수리 (담당 설비팀장 박민수, 기한 ' || to_char(GREATEST(pg_temp.saife_wd((pg_temp.saife_wd((CURRENT_DATE - 60)) + 7)), pg_temp.saife_next(pg_temp.saife_wd((CURRENT_DATE - 60)))), 'YYYY-MM-DD') || ')' || chr(10) || '2. 창고동 출입구 보행 통로 구획선 도색 (담당 창고반장 최동훈, 기한 ' || to_char(GREATEST(pg_temp.saife_wd((pg_temp.saife_wd((CURRENT_DATE - 60)) + 14)), pg_temp.saife_next(pg_temp.saife_wd((CURRENT_DATE - 60)))), 'YYYY-MM-DD') || ')', NULL, 'NOT_REQUIRED', 22, ((pg_temp.saife_wd((CURRENT_DATE - 60)) + TIME '17:31') AT TIME ZONE 'Asia/Seoul')),
  (5, 1, 13, NULL, ((pg_temp.saife_wd((CURRENT_DATE - 150)) + TIME '15:20') AT TIME ZONE 'Asia/Seoul'), '한OO', 'LOST_TIME', 6, 'FIRE', 'CO2 용접 중 불티가 작업대 아래 유기용제 묻은 걸레에 옮겨 붙었고, 불을 끄던 작업자가 오른손등에 화상', '불안전 상태: 용접 작업 반경 안에 유기용제 묻은 걸레가 있었고 방화포가 없었음' || chr(10) || '불안전 행동: 화재감시자 없이 1인으로 용접함', '1. 용접 반경 안 유기용제, 걸레 반입 금지 표지와 정리 (담당 용접반장 정민준, 기한 ' || to_char(GREATEST(pg_temp.saife_wd((pg_temp.saife_wd(((date_trunc('month', CURRENT_DATE) - INTERVAL '6 months')::date + 9)) + 14)), pg_temp.saife_next(pg_temp.saife_wd(((date_trunc('month', CURRENT_DATE) - INTERVAL '6 months')::date + 9)))), 'YYYY-MM-DD') || ')' || chr(10) || '2. 용접 작업 시 화재감시자 배치, 방화포 사용 (담당 용접반장 정민준, 기한 ' || to_char(GREATEST(pg_temp.saife_wd((pg_temp.saife_wd((CURRENT_DATE - 150)) + 7)), pg_temp.saife_next(pg_temp.saife_wd((CURRENT_DATE - 150)))), 'YYYY-MM-DD') || ')' || chr(10) || '3. 용접구역 유기용제 걸레 전용 밀폐 용기 비치 (담당 용접반장 정민준, 기한 ' || to_char(GREATEST(pg_temp.saife_wd((pg_temp.saife_wd((CURRENT_DATE - 150)) + 14)), pg_temp.saife_next(pg_temp.saife_wd((CURRENT_DATE - 150)))), 'YYYY-MM-DD') || ')', (pg_temp.saife_wd((CURRENT_DATE - 150)) + INTERVAL '1 month')::date, 'SUBMITTED', 23, ((pg_temp.saife_wd((CURRENT_DATE - 150)) + TIME '15:57') AT TIME ZONE 'Asia/Seoul')),
  (6, 1, 16, 37, ((pg_temp.saife_wd((CURRENT_DATE - 20)) + TIME '09:50') AT TIME ZONE 'Asia/Seoul'), '서OO', 'LOST_TIME', 42, 'DROP', '금형(약 1.2톤) 인양 중 해지장치가 부러진 훅에서 슬링 한쪽이 벗겨져 금형이 기울며 흔들렸고, 기운 금형 모서리가 신호수 오른발등을 침, 중족골 골절', '불안전 상태: 훅 해지장치 스프링이 부러져 있었고, 인양물 주변 출입 통제선이 없었음' || chr(10) || '불안전 행동: 인양 전 해지장치를 확인하지 않고 인양했고, 신호수가 인양물 가까이 서 있었음', '1. 천장크레인 훅 해지장치 교체 (담당 설비팀장 박민수, 기한 ' || to_char(GREATEST(pg_temp.saife_wd((pg_temp.saife_wd((CURRENT_DATE - 20)) + 1)), pg_temp.saife_next(pg_temp.saife_wd((CURRENT_DATE - 20)))), 'YYYY-MM-DD') || ')' || chr(10) || '2. 줄걸이 용구 사용 전 점검표 도입, 인양 전 해지장치 확인 (담당 용접반장 정민준, 기한 ' || to_char(pg_temp.saife_wd((CURRENT_DATE + 3)), 'YYYY-MM-DD') || ')' || chr(10) || '3. 인양 작업 신호수 위치 지정, 인양물 주변 출입 금지 교육 (담당 안전관리자 홍길동, 기한 ' || to_char(pg_temp.saife_wd((CURRENT_DATE + 25)), 'YYYY-MM-DD') || ')', (pg_temp.saife_wd((CURRENT_DATE - 20)) + INTERVAL '1 month')::date, 'REQUIRED', 24, ((pg_temp.saife_wd((CURRENT_DATE - 20)) + TIME '11:17') AT TIME ZONE 'Asia/Seoul'));
SELECT setval('incident_id_seq', 6, true);

DROP FUNCTION pg_temp.saife_prev(date);
DROP FUNCTION pg_temp.saife_next(date);
DROP FUNCTION pg_temp.saife_wd(date);

